// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Serial { get; set; }

    public string CarNum { get; set; }

    public string Manufacturer { get; set; }

    public int EnginePower { get; set; }

    public int PassengersAmount { get; set; }

    public double Weight { get; set; }

    public string Color { get; set; }

    public string BodyType { get; set; }

    public bool Conditioner { get; set; }

    public virtual ICollection<ClientCar> ClientCars { get; set; } = new List<ClientCar>();

    public virtual ICollection<ContractCar> ContractCars { get; set; } = new List<ContractCar>();

    public override string ToString() => $"[{CarId}] : {Manufacturer} {Serial} {CarNum}";

    public void CopyFromCustomView(CustomViews.CustomViewCar customViewCar)
    {
        CarId = customViewCar.CarId;
        Serial = customViewCar.Serial;
        CarNum = customViewCar.CarNum;
        Manufacturer = customViewCar.Manufacturer;
        EnginePower = customViewCar.EnginePower;
        PassengersAmount = customViewCar.PassengersAmount;
        Weight = customViewCar.Weight;
        Color = customViewCar.Color;
        BodyType = customViewCar.BodyType;
        Conditioner = customViewCar.Conditioner;

        foreach(var owner in customViewCar.Owners)
        {
            ClientCar clientCar = new()
            {
                CarId = CarId,
                Client = owner
            };
        }
    }
}