// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class Contract
{
    public int ContractId { get; set; }

    public DateOnly ConclusionDate { get; set; }

    public int ClientId { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<ContractCar> ContractCars { get; set; } = new List<ContractCar>();

    public virtual ICollection<ContractService> ContractServices { get; set; } = new List<ContractService>();
}