// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class ContractCar
{
    public int ContractCarId { get; set; }

    public int ContractId { get; set; }

    public int CarId { get; set; }

    public virtual Car Car { get; set; }

    public virtual Contract Contract { get; set; }
}