// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Cars.Models.CustomViews;
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class Craftsman
{
    public int CraftsmanId { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string MiddleName { get; set; }

    public int Expirience { get; set; }

    public int CenterId { get; set; }

    public virtual ServiceCenter Center { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public override string ToString() => $"[{CraftsmanId} : {SecondName} {FirstName}]";

    public void CopyFromCustomView(CustomViewCraftsman customViewCraftsman)
    {
        CraftsmanId = customViewCraftsman.CraftsmanId;
        FirstName = customViewCraftsman.FirstName;
        SecondName = customViewCraftsman.SecondName;
        MiddleName = customViewCraftsman.MiddleName;
        Expirience = customViewCraftsman.Expirience;

        Center = customViewCraftsman.ServiceCenter;
    }
}