// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Cars.Models.CustomViews;
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public string ServiceType { get; set; }

    public decimal Cost { get; set; }

    public int CenterId { get; set; }

    public virtual ServiceCenter Center { get; set; }

    public virtual ICollection<ContractService> ContractServices { get; set; } = new List<ContractService>();

    public override string ToString() => $"[{ServiceId}] : {ServiceType} - {Cost}";

    public void CopyFromCustomView(CustomViewService customViewService)
    {
        ServiceId = customViewService.ServiceId;
        ServiceType = customViewService.ServiceType;
        Cost = customViewService.Cost;

        Center = customViewService.ServiceCenter;
    }
}