// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cars.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Role { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int? ClientId { get; set; }

    public int? CraftsmanId { get; set; }

    public virtual Client Client { get; set; }

    public virtual Craftsman Craftsman { get; set; }
}